Define package of the class before defining the class in JetClassLoader
hazelcast/hazelcast-jet pull request #2566
Opened 2020-09-25 15:27 UTC by gurbuzali

Currently JetClassLoader loads the configured classes but does not define their 
packages. According to the javadoc of `ClassLoader#definePackage` it should
be defined prior to definig the class:

```
     * Defines a package by name in this <tt>ClassLoader</tt>.  This allows
     * class loaders to define the packages for their classes. Packages must
     * be created before the class is defined, and package names must be
     * unique within a class loader and cannot be redefined or changed once
     * created.
```

Not defining the package results in issues for the avro, the implementation
relies on that the package of the class while creating the schema.

Checklist
- [X] Labels and Milestone set
- [NA] Breaking changes documented
- [NA] New public APIs have `@Nonnull/@Nullable` annotations
- [NA] New public APIs have `@since` tags in Javadoc
- [NA] For code samples, code sample main readme is updated

2020-09-28 08:22 UTC, viliam-durina requested changes

2020-09-28 08:22 UTC, viliam-durina commented on hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
> +        if (getPackage(packageName) != null) {
This method was deprecated in java9. I've read a bit why, but am not sure how to fix it in java8. But it's only an issue if multiple class loaders define the same packages, but I'd say it's not common. The purpose of defining the package is to make package annotations available, and if one uses package annotations, he doesn't use a package name that's likely to be used in some other library...

So consider this comment just a thinking aloud, we can live with this code for a while :)

2020-09-28 08:22 UTC, viliam-durina commented on hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
> +                    clPackage.getImplementationVersion(), clPackage.getImplementationVendor(), null);
This is certainly not correct. I'm not sure but i think that the values need to be loaded from the manifest file, or rather we can just pass in nulls, as I saw in several examples on the web. We certainly should not pass jet's meta informations to user's packages.

2020-09-28 08:24 UTC, viliam-durina commented on hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java
> +        if (getPackage(packageName) != null) {
Maybe we can rather rely on ignoring the `IArgExc`. Or re-verify there just, as `URLClassLoader` does.

2020-09-30 05:54 UTC, hz-highfive commented
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3390/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3390/jet-oss-pr-builder-3390.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:checkstyle (default) on project hazelcast-jet-core: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 errors reported by Checkstyle 8.29 with /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/checkstyle/checkstyle.xml ruleset. -> [Help 1]
--------------------------
---------ERRORS-----------
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java:106:50: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
[ERROR] /home/jenkins/jenkins_slave/workspace/jet-oss-pr-builder/hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/deployment/JetClassLoader.java:106:61: ',' is not followed by whitespace. [WhitespaceAfter]
--------------------------
</details>
</pre>

2020-09-30 07:27 UTC, viliam-durina approved these changes

2020-10-01 10:03 UTC, merged