4.3 Release Notes and Changelog
hazelcast/hazelcast-jet pull request #2577
Opened 2020-09-30 11:12 UTC by mtopolnik

2020-09-30 19:50 UTC, cangencer commented on hazelcast-jet-distribution/src/root/release_notes.txt
> +** Hazelcast Jet 4.3 **
Are these all?

* IMDG version is updated
* I can see many other bugs fixed: https://github.com/hazelcast/hazelcast-jet/pulls?q=is%3Apr+milestone%3A4.3+is%3Aclosed+label%3Adefect but only 1 is mentioned here?

2020-10-01 06:53 UTC, jbartok requested changes

2020-10-01 06:53 UTC, jbartok commented on hazelcast-jet-distribution/src/root/release_notes.txt
> +[core] [013] Avoid problem where low event rate would stall progress of a processing time-based pipeline (#2485, #2514)
Maybe mention the addition of configurable reconnect strategies for CDC sources?

2020-10-01 06:53 UTC, jbartok commented on hazelcast-jet-distribution/src/root/release_notes.txt
> +
Maybe mention the integration of a Jackson-jr bug-fix, which was affecting our JSON-to-POJO mapping, specifically in CDC (https://github.com/FasterXML/jackson-jr/issues/73).

Also, integration of a Debezium fix which solved the problem of losing data on snapshotting in CDC sources for Postgres (https://issues.redhat.com/browse/DBZ-2288).

2020-10-01 10:55 UTC, hz-highfive commented
The job `jet-oss-pr-builder-docs-no-build` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/295/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/295/jet-oss-pr-builder-docs-no-build-295.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
There are unexpected files.
Unexpected file: NOTICE
</details>
</pre>

2020-10-01 12:04 UTC, jbartok approved these changes

2020-10-01 13:23 UTC, hz-highfive commented
The job `jet-oss-pr-builder-docs-no-build` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/297/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder-docs-no-build/297/jet-oss-pr-builder-docs-no-build-297.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
---------SUMMARY----------
--------------------------
There are unexpected files.
Unexpected file: NOTICE
</details>
</pre>

2020-10-02 06:17 UTC, jbartok commented on hazelcast-jet-distribution/src/root/release_notes.txt
> +[cdc] Upgraded Jackson jr dep, solving a null handling issue (#2459)
This was in fact a more generic, JSON handling problem, just more obvious in the context of CDC. Now, if that's worth mentioning or not, that's your call. Just saying.

2020-10-19 08:50 UTC, olukas commented
verify

2020-10-19 10:44 UTC, merged