Add logging for job status after job submit
hazelcast/hazelcast-jet pull request #2699
Opened 2020-11-23 08:25 UTC by ufukyilmaz

Fixes #2426 
Checklist:
- [x] Labels and Milestone set

2020-11-23 08:28 UTC, ufukyilmaz commented on hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
> +                    .filter(job -> !jobsBeforeSubmit.contains(job))
Here, I couldn't manage how to filter jobs submitted from a different client in a proper way.

2020-11-23 08:42 UTC, hz-highfive commented
The job `jet-oss-pr-builder` of your PR failed ([log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3645/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/3645/jet-oss-pr-builder-3645.zip)). 
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JetCommandLineTest.testTargetsMixin:519->testTargetsCommand:547->testTargetsCommandCluster:564 NullPointer
[ERROR]   JetCommandLineTest.test_submit_clientShutdownWhenDone:452->run:666 ? Execution
[INFO] 
[ERROR] Tests run: 39, Failures: 0, Errors: 2, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</details>
</pre>

2020-11-26 11:22 UTC, viliam-durina reviewed
I'm not sure this is what we wanted. Remember, the `main` method we called can do whatever. It can start and cancel jobs in a loop, it can never return. It might submit a batch job and join it: we'll still print `Job started.` even though the job is already over...

I imagined something simpler. When `newJob` returns just print `Job 1234-1234-1234-1234 submitted`. Or `Job 'foo' submitted.`, if the job has a name.

What others think?

2020-12-24 09:33 UTC, mtopolnik commented
I'm OK with Vilo's idea. @frant-hartm what do you think?

2021-01-05 07:47 UTC, frant-hartm requested changes

2021-01-05 07:47 UTC, frant-hartm commented on hazelcast-jet-core/src/main/java/com/hazelcast/jet/impl/JetBootstrap.java
> +                }
I think a date would be useful for debugging - e.g. when there is a large pause between submission and change to running state.

2021-01-05 07:48 UTC, frant-hartm commented
This is basically what I asked for in the issue, so :+1:  from me.

Maybe the waiting for jobs to run/fail could be hidden behind an option though and the default would just print what vilo says.

2021-01-12 09:41 UTC, mtopolnik commented
Printing something when starting every job may also backfire if you start many jobs. You'll get too much noise in the output. Submitting jobs should primarily be a fire-and-forget thing, but maybe we can in the future add an option to await the completion of all the started jobs, as well as cancelling them if interrupted with ctrl-c. Then the user who wants that behavior won't have to write the quite tricky boilerplate to get it.

2021-01-14 08:26 UTC, frant-hartm approved these changes

2021-01-14 08:27 UTC, merged