Update to Hazelcast IMDG 4.2.6 [HZ-1438]
hazelcast/hazelcast-jet pull request #3125
Opened 2022-11-25 09:58 UTC by kwart

This PR updates the underlying Hazelcast IMDG version to the new `4.2.6` one.

2022-11-25 10:03 UTC, olukas approved these changes

2022-11-28 11:48 UTC, frant-hartm requested changes
This PR should go to `4.5-maintenance` branch.

2022-11-29 10:51 UTC, hz-devops-test commented
The job `jet-oss-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4349/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4349/jet-oss-pr-builder-4349.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   S3MockTest.com.hazelcast.jet.s3.S3MockTest ? ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-11-29 10:53 UTC, hz-devops-test commented
The job `jet-oss-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4350/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4350/jet-oss-pr-builder-4350.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   S3MockTest.com.hazelcast.jet.s3.S3MockTest ? ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-12-05 09:06 UTC, hz-devops-test commented
The job `jet-oss-pr-builder` of your PR failed. (Hazelcast internal details: [build log](
https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4372/build_log.txt), [artifacts](https://j-artifacts.s3.amazonaws.com/jet-oss-pr-builder/4372/jet-oss-pr-builder-4372.zip)).
Through arcane magic we have determined that the following fragments from the build log may contain information about the problem.
<details>
<summary>Click to expand the log file</summary>
<pre>
--------------------------
-------TEST FAILURE-------
--------------------------
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   WriteJdbcPTest.com.hazelcast.jet.impl.connector.WriteJdbcPTest ? ContainerLaunch
[INFO] 
[ERROR] Tests run: 2453, Failures: 0, Errors: 1, Skipped: 10
[INFO] 

[ERROR] There are test failures.
</pre>
</details>

2022-12-05 14:58 UTC, TomaszGaweda commented
Already merged in #3120

2022-12-05 14:58 UTC, closed without merging